
owner: nutrio
repo: status
sites:
  - name: Website
    url: https://nutriot.com
  - name: Bandcamp
    url: https://nutriot.bandcamp.com
  - name: SoundCloud
    url: https://soundcloud.com/nutriot
    
status-website:
  cname: nutriot.github.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nutriot Recordings
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
