# Change these first
owner: nutriot # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Website
    url: https://nutriot.com
  - name: Bandcamp
    url: https://nutriot.bandcamp.com
  - name: SoundCloud
    url: https://soundcloud.com/nutriot
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  baseUrl: /status
  name: Nutriot Recordings
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
